/**
 * TinyCardio INT8 Serialized Model Weights
 * Automatically generated by quantize_int8.py
 * Target Architectures: ARM Cortex-M0+ (RP2040), Cortex-M4 (STM32), ESP32-C3
 * Flash Memory Footprint: 540 bytes
 */

#ifndef MODEL_WEIGHTS_H
#define MODEL_WEIGHTS_H

#include <stdint.h>

#define TINYCARDIO_INPUT_LEN       250
#define TINYCARDIO_CONV1_KERNEL    5
#define TINYCARDIO_CONV1_IN_CH     1
#define TINYCARDIO_CONV1_OUT_CH    8
#define TINYCARDIO_CONV1_STRIDE    2
#define TINYCARDIO_CONV1_OUT_LEN   125

#define TINYCARDIO_CONV2_KERNEL    3
#define TINYCARDIO_CONV2_IN_CH     8
#define TINYCARDIO_CONV2_OUT_CH    16
#define TINYCARDIO_CONV2_STRIDE    2
#define TINYCARDIO_CONV2_OUT_LEN   63

#define TINYCARDIO_DENSE_IN_FEAT   16
#define TINYCARDIO_DENSE_OUT_FEAT  1

/* Scaling Factors for Weights */
#define TINYCARDIO_SCALE_CONV1     0.01325763f
#define TINYCARDIO_SCALE_CONV2     0.01447827f
#define TINYCARDIO_SCALE_DENSE     0.01075345f
#define TINYCARDIO_TOTAL_WEIGHTS_BYTES 540

/* Layer 1: Conv1D Weights (INT8) and Bias (Float) */
static const int8_t g_tinycardio_conv1_w[40] = {
    -47, 18, 119, 29, 28, 9, 46, -34, -127, 64, 55, 11, 79, 0, 8, -28, 10, 51, -14, 66, -105, 3, -41, 57, 59, 69, 99, 55, 65, -99, -26, -6, 104, 54, -20, 63, 5, -51, -105, 30
};

static const float g_tinycardio_conv1_b[8] = {
    0.021888f, 0.389747f, 0.248600f, 0.172372f, 0.449439f, -0.494265f, -0.441896f, 0.451647f
};


/* Layer 2: Conv1D Weights (INT8) and Bias (Float) */
static const int8_t g_tinycardio_conv2_w[384] = {
    47, 43, -86, -19, 0, 34, 14, -15, 32, 1, -65, -48, -7, 38, 1, 31, -46, -16, -17, -37, -54, 24, -15, 19, -31, -12, 34, 40, 30, -61, -4, -71, -59, -44, -26, -74, 15, -23, -3, 5, -75, 16, 16, 6, -5, -127, 68, -21, -3, -26, -11, -35, -38, 3, -12, 32, -36, 6, -5, 11, 18, -56, 15, -67, -41, -80, -12, -5, 20, -29, -32, 8, -84, -3, 65, 22, 32, -61, 1, -9, 24, 37, -5, -31, 45, -52, 13, -11, 38, 26, -102, 27, 16, 2, -1, 59, 15, 24, 49, -16, 41, -38, -24, 19, 43, 18, -35, 21, -14, 32, 6, 7, -49, -7, -61, 55, 18, -3, -4, 35, -14, -125, 20, -20, 9, 33, 30, 38, 11, -11, -28, -5, 55, 45, 56, 0, 46, 24, -45, -55, -36, 75, 10, 79, -15, 16, 0, -5, -88, 40, 6, 2, -11, -33, 13, 8, -1, -22, -44, -14, -23, -8, 10, -72, -56, 29, 11, -2, -8, -26, 32, 41, 28, -50, -13, -59, -34, -24, -25, -52, -25, 25, 16, -38, 7, -17, -2, 19, -24, -28, -37, -6, -40, -11, -20, 4, -40, -38, -5, 1, -33, -30, 29, 25, 45, -10, 19, -42, 43, 35, 17, -24, -19, 23, 28, 17, 60, -5, -58, -12, 23, 10, 34, -12, 36, 34, 27, 37, 19, 39, -2, 11, 22, -3, -57, -15, -6, -15, 27, 5, -46, -43, -23, 42, 26, 3, 2, 7, -32, -31, 10, 1, 13, 22, -24, 29, -46, -62, 65, -36, 90, 4, 33, -42, -55, 34, 16, 8, -17, 27, 98, 38, 20, 5, -20, -2, 7, -27, -16, -32, -12, 10, 46, 26, 5, 30, -12, 5, 45, 10, 20, -35, 6, 37, -8, -7, 45, 1, 2, 49, -8, 16, -59, 1, -41, -15, 15, -25, 6, -42, 40, -56, -80, 11, 17, -10, 52, 44, -41, 36, 30, -1, -1, -4, -37, -23, 34, -24, 57, -10, 26, 22, 14, -6, 7, -19, 19, 42, -26, -7, -39, 19, -32, 25, 44, -24, -63, 38, 38, -51, -32, -29, 59, 19, -39, 19, -39, 25, 16, 42, 75, 3, -77, -25, -3, -5, -28, -41, -47, -60, 7, 51, 50, 29, 26, -14, -38, 22, 14, 5, -3, 42, 25, 18
};

static const float g_tinycardio_conv2_b[16] = {
    -0.213166f, -0.243486f, -0.158866f, 0.534736f, 0.129293f, -0.222415f, -0.093227f, 0.051182f, -0.434606f, -0.302733f, 0.349427f, 0.121995f, 0.066534f, 0.188994f, 0.229400f, 0.095661f
};


/* Layer 3: Dense Weights (INT8) and Bias (Float) */
static const int8_t g_tinycardio_dense_w[16] = {
    75, 96, -81, -76, -64, -127, -75, -24, 41, -103, 108, 25, 50, -55, -107, -110
};

static const float g_tinycardio_dense_b[1] = {
    0.065459f
};


#endif /* MODEL_WEIGHTS_H */
