/**
 * TinyCardio INT8 Serialized Model Weights
 * Automatically generated by quantize_int8.py
 * Target Architectures: ARM Cortex-M0+ (RP2040), Cortex-M4 (STM32), ESP32-C3
 * Flash Memory Footprint: 540 bytes
 */

#ifndef MODEL_WEIGHTS_H
#define MODEL_WEIGHTS_H

#include <stdint.h>

#define TINYCARDIO_INPUT_LEN       250
#define TINYCARDIO_CONV1_KERNEL    5
#define TINYCARDIO_CONV1_IN_CH     1
#define TINYCARDIO_CONV1_OUT_CH    8
#define TINYCARDIO_CONV1_STRIDE    2
#define TINYCARDIO_CONV1_OUT_LEN   125

#define TINYCARDIO_CONV2_KERNEL    3
#define TINYCARDIO_CONV2_IN_CH     8
#define TINYCARDIO_CONV2_OUT_CH    16
#define TINYCARDIO_CONV2_STRIDE    2
#define TINYCARDIO_CONV2_OUT_LEN   63

#define TINYCARDIO_DENSE_IN_FEAT   16
#define TINYCARDIO_DENSE_OUT_FEAT  1

/* Scaling Factors for Weights */
#define TINYCARDIO_SCALE_CONV1     0.01178622f
#define TINYCARDIO_SCALE_CONV2     0.01323811f
#define TINYCARDIO_SCALE_DENSE     0.01543574f
#define TINYCARDIO_TOTAL_WEIGHTS_BYTES 540

/* Layer 1: Conv1D Weights (INT8) and Bias (Float) */
static const int8_t g_tinycardio_conv1_w[40] = {
    -30, -13, 84, 20, 28, 26, 26, -13, -127, 45, 23, -5, 90, 14, -4, -11, -6, 35, -40, 55, -118, 22, -40, 79, 20, 58, 98, 42, 71, -89, -4, 2, 70, 38, -38, 54, -3, -36, -80, 34
};

static const float g_tinycardio_conv1_b[8] = {
    -0.690033f, 0.236374f, -0.066420f, -0.110721f, 0.422352f, -0.175364f, -0.016209f, 0.055596f
};


/* Layer 2: Conv1D Weights (INT8) and Bias (Float) */
static const int8_t g_tinycardio_conv2_w[384] = {
    44, -23, -27, -15, -28, 40, -4, -22, 51, -1, -97, -25, 14, 4, -23, 1, -23, 15, -12, -21, -14, 18, -11, 18, -19, -4, 28, 30, 23, -81, -2, -75, -27, 11, -22, -54, 19, -75, 10, -12, -55, 14, 4, -4, -14, -72, 72, 66, 12, -6, -9, 25, 0, -3, -11, 34, -53, 13, -13, 2, 10, -53, 23, -46, -5, -16, 2, -13, 28, -109, -17, -17, -53, 3, 56, 5, 23, -75, -1, 38, -1, 1, -40, -24, 35, -33, 10, 6, 16, 14, 16, 22, -1, -4, 26, 52, 3, 1, 18, -38, 28, -25, -25, 27, 36, 4, 0, 23, -23, 31, 16, -23, -23, 8, -31, 16, 0, 2, -3, 30, 34, -74, 22, -26, 10, 10, 14, 23, 25, -55, -53, 0, 7, 43, 36, -4, 70, -2, -61, -43, -23, 42, -45, 46, 24, 27, 12, -10, -60, 48, 4, 15, 12, -23, 7, -4, -11, -32, -52, -9, -11, 14, 16, -26, -5, 25, 16, -4, -25, -16, 28, 34, 20, -56, -5, -53, -49, -16, -20, -41, 3, 34, 16, -20, -19, -10, -9, 8, -36, -30, -31, 9, -29, 24, 5, -15, -10, -61, 4, -14, -9, -7, 24, 9, 36, -75, 24, -127, 24, 12, -2, -26, -18, 14, 37, 25, 46, -11, -34, -16, 16, 23, 53, 5, 26, 21, 11, 18, 16, 28, 6, 12, 14, -10, -42, -13, -7, -7, 35, -8, -10, -11, -17, 1, -6, 9, -9, 5, 33, -19, 6, 2, 17, -4, -94, 15, 1, -11, 28, -26, 53, -5, 12, -55, 2, 6, -8, 27, -28, -8, 41, 29, 26, 21, -17, -17, 3, -34, -24, -37, 2, 9, 41, 19, -5, 30, -55, 19, 38, 12, 34, -16, 35, 49, -10, 12, 28, 12, -4, 41, -19, 20, -70, 20, -61, 7, 18, -14, 2, -47, 40, -40, -125, 10, 8, -22, 46, 48, -81, 55, 44, 1, 26, -19, -18, -23, 39, -28, 98, 13, 17, 2, 3, -49, 9, -55, -11, 9, -2, -22, -2, 19, -16, 29, 16, -16, -63, 42, 43, -13, -7, -1, 40, -5, -28, -12, -22, 17, 31, 44, 56, 11, -78, -20, 5, 26, -18, -48, -11, 19, -25, 12, 23, 36, 16, -23, 9, 20, 4, 12, -7, 24, -32, 18
};

static const float g_tinycardio_conv2_b[16] = {
    -0.109614f, 0.044604f, 0.003388f, -0.040655f, -0.064687f, -0.366392f, -0.038585f, -0.024570f, -0.203820f, -0.132455f, 0.238754f, -0.001569f, 0.080933f, 0.011583f, 0.319990f, -0.544190f
};


/* Layer 3: Dense Weights (INT8) and Bias (Float) */
static const int8_t g_tinycardio_dense_w[16] = {
    21, 16, -25, -10, -9, -127, -41, -14, 8, -42, 69, 2, 23, -14, -76, -85
};

static const float g_tinycardio_dense_b[1] = {
    0.047983f
};


#endif /* MODEL_WEIGHTS_H */
