/**
 * TinyCardio INT8 Serialized Model Weights
 * Automatically generated by quantize_int8.py
 * Target Architectures: ARM Cortex-M0+ (RP2040), Cortex-M4 (STM32), ESP32-C3
 * Flash Memory Footprint: 540 bytes
 */

#ifndef MODEL_WEIGHTS_H
#define MODEL_WEIGHTS_H

#include <stdint.h>

#define TINYCARDIO_INPUT_LEN       250
#define TINYCARDIO_CONV1_KERNEL    5
#define TINYCARDIO_CONV1_IN_CH     1
#define TINYCARDIO_CONV1_OUT_CH    8
#define TINYCARDIO_CONV1_STRIDE    2
#define TINYCARDIO_CONV1_OUT_LEN   125

#define TINYCARDIO_CONV2_KERNEL    3
#define TINYCARDIO_CONV2_IN_CH     8
#define TINYCARDIO_CONV2_OUT_CH    16
#define TINYCARDIO_CONV2_STRIDE    2
#define TINYCARDIO_CONV2_OUT_LEN   63

#define TINYCARDIO_DENSE_IN_FEAT   16
#define TINYCARDIO_DENSE_OUT_FEAT  1

/* Scaling Factors for Weights */
#define TINYCARDIO_SCALE_CONV1     0.01100222f
#define TINYCARDIO_SCALE_CONV2     0.01376779f
#define TINYCARDIO_SCALE_DENSE     0.01621938f
#define TINYCARDIO_TOTAL_WEIGHTS_BYTES 540

/* Layer 1: Conv1D Weights (INT8) and Bias (Float) */
static const int8_t g_tinycardio_conv1_w[40] = {
    -28, 3, 127, 21, 31, 0, 67, 0, -109, 60, 46, -1, 97, -2, 20, 6, 33, 46, -33, 65, -123, 12, -42, 103, 59, 70, 113, 53, 81, -105, -25, 18, 112, 56, -23, 67, 4, -47, -114, 50
};

static const float g_tinycardio_conv1_b[8] = {
    -0.442214f, 0.378982f, 0.294661f, -0.175424f, 0.313485f, -0.381175f, -0.602650f, 0.248245f
};


/* Layer 2: Conv1D Weights (INT8) and Bias (Float) */
static const int8_t g_tinycardio_conv2_w[384] = {
    57, -8, -75, -16, 4, 34, -7, -6, 63, 16, -54, -35, 10, 10, -17, 10, -22, 24, -11, -22, -36, 25, -13, 17, -19, -14, 31, 39, 29, -24, -2, -43, -42, 22, -8, -52, 51, -33, 7, -7, -67, 15, 12, 7, -7, -62, 87, 18, 0, 5, -9, 24, -12, 2, -13, 32, -51, 7, -9, 9, 16, -16, 19, -38, -17, -7, 12, -12, 42, -35, -19, -1, -71, -2, 59, 18, 27, -23, 14, 14, 16, 11, -13, -23, 26, -33, 12, -3, 38, 14, -104, 29, 13, -12, -2, 35, 11, -1, 74, -37, 61, -50, -26, 20, 45, 25, -23, 17, -19, 32, 41, 23, -16, 20, -30, 14, -60, -2, -9, 27, 29, -114, 26, -16, 19, 25, -1, 32, 39, -25, -33, 0, 74, 50, 39, -15, 94, 35, -42, -46, -19, 51, 70, 64, -10, 32, 2, -10, -83, 45, 6, 3, -32, -28, 12, 4, -4, 1, -66, 11, -14, 28, 15, -26, -39, 27, 12, -9, -17, -29, 33, 44, 30, -10, -20, -27, -64, -8, -23, -40, -2, 28, 16, -37, -36, -11, -4, 15, -28, -7, -39, 18, -26, 35, -9, -13, -68, -43, 0, -6, -26, -29, 25, 22, 45, 23, -10, -24, 37, 13, 7, -22, -13, -2, 34, 19, 60, -6, -53, -9, 25, 12, 32, -14, 34, 11, 34, 18, 42, 35, 2, 12, 27, 0, -69, -19, -10, -11, 58, 28, -6, 2, -59, 0, -17, 6, 0, -20, 23, -21, 12, 2, 25, 15, -78, 28, -24, -17, 86, -23, 103, -28, 18, -57, -48, 36, 19, 18, -15, 2, 127, 33, 25, 17, -22, -16, 6, -25, -18, -40, -16, 10, 44, 20, -1, 47, 28, 23, 43, 23, 22, -15, 15, 39, -8, -14, 23, 6, 3, 50, -8, 37, -87, 24, -75, 5, 17, -14, 11, -41, 41, -59, -99, 13, 13, -18, 48, 60, 5, 56, 36, 13, 3, -16, -61, -24, 39, -32, 54, -3, 24, 16, 11, 20, -44, 3, 6, 12, -36, -22, -34, 9, -17, 26, 34, -24, -55, 48, 44, -39, -48, -42, 51, -14, -53, -9, -50, 30, 31, 44, 75, 8, -79, -26, -4, 24, -35, -3, -13, 17, -15, 12, 38, 35, 26, -53, 0, 31, 6, 7, 0, 37, 43, 21
};

static const float g_tinycardio_conv2_b[16] = {
    0.029112f, 0.099620f, -0.397231f, -0.057495f, -1.015493f, -0.301243f, -0.167690f, -0.072635f, -0.058649f, -0.308928f, 0.207061f, 0.088558f, 0.108205f, 0.094094f, -1.185574f, -0.446443f
};


/* Layer 3: Dense Weights (INT8) and Bias (Float) */
static const int8_t g_tinycardio_dense_w[16] = {
    32, 23, -62, -6, -56, -80, -41, -16, 18, -65, 62, 15, 32, -16, -127, -62
};

static const float g_tinycardio_dense_b[1] = {
    0.108519f
};


#endif /* MODEL_WEIGHTS_H */
