#!/usr/bin/env python3
"""
TinyCardio Rural Triage & SMS Telemetry Hub (Pilar 2)
====================================================
Microservice that receives ultra-low bandwidth 2G SMS payloads (<60 bytes)
from TinyCardio Edge Nodes ($4.30 USD), associates them with pre-registered
rural patient medical records, and broadcasts real-time events to the
Web Emergency Dispatch Dashboard via REST and Server-Sent Events (SSE).

Features:
  - Zero third-party dependencies (Pure Python standard library)
  - Full CORS support for React / Vue / Mobile web frontends
  - Real-time Server-Sent Events (SSE) streaming (/api/alerts/stream)
  - Pre-registered rural patient registry (GIS coordinates, history, contact)
  - Golden Hour (1-hour) countdown & triage severity classifier
  - Bi-directional return SMS dispatcher for ambulance reassurance
"""

import sys
import os
import json
import time
import re
import threading
from http.server import HTTPServer, BaseHTTPRequestHandler
from urllib.parse import urlparse, parse_qs

# Pre-registered rural patient database (Typical Latin America / Global South rural community health registry)
MOCK_PATIENTS = {
    1024: {
        "device_id": 1024,
        "name": "María Quispe Huamán",
        "age": 62,
        "gender": "Femenino",
        "blood_type": "O+",
        "location_name": "Vereda El Roble, Sector Alto (Km 14)",
        "coordinates": {"lat": -13.5320, "lng": -71.9675},
        "medical_history": "Infarto previo en 2024, Hipertensión arterial estadio II",
        "current_medication": "Enalapril 10mg, Aspirina 100mg",
        "emergency_contact": "Hijo: Juan Quispe (+51 984 551 203)",
        "assigned_chw": "Promotora Rosa Medina (ID: CHW-04)",
        "device_battery_pct": 89
    },
    2048: {
        "device_id": 2048,
        "name": "Carlos Mamani Condori",
        "age": 58,
        "gender": "Masculino",
        "blood_type": "A+",
        "location_name": "Comunidad Campesina San Pedro (Chacra 3)",
        "coordinates": {"lat": -13.5412, "lng": -71.9540},
        "medical_history": "Diabetes Mellitus Tipo 2, Angina de pecho estable",
        "current_medication": "Metformina 850mg, Atorvastatina 20mg",
        "emergency_contact": "Esposa: Elena Mamani (+51 987 112 450)",
        "assigned_chw": "Promotor Mateo Huanca (ID: CHW-02)",
        "device_battery_pct": 74
    },
    3072: {
        "device_id": 3072,
        "name": "Esperanza Flores Ticona",
        "age": 71,
        "gender": "Femenino",
        "blood_type": "B+",
        "location_name": "Caserío Monte Verde (Ribera del Río)",
        "coordinates": {"lat": -13.5205, "lng": -71.9780},
        "medical_history": "Insuficiencia Cardíaca Congestiva (NYHA II), Marcapasos bicameral",
        "current_medication": "Furosemida 40mg, Carvedilol 6.25mg",
        "emergency_contact": "Hija: Lucía Flores (+51 950 334 118)",
        "assigned_chw": "Promotora Rosa Medina (ID: CHW-04)",
        "device_battery_pct": 92
    },
    4096: {
        "device_id": 4096,
        "name": "José David Morales",
        "age": 49,
        "gender": "Masculino",
        "blood_type": "O-",
        "location_name": "Sector La Esperanza (Camino Rural Principal)",
        "coordinates": {"lat": -13.5280, "lng": -71.9490},
        "medical_history": "Tabaquismo severo, hipercolesterolemia familiar",
        "current_medication": "Rosuvastatina 20mg",
        "emergency_contact": "Hermano: Pedro Morales (+51 981 776 502)",
        "assigned_chw": "Promotor Mateo Huanca (ID: CHW-02)",
        "device_battery_pct": 68
    }
}

# In-memory alert state storage
ALERTS_LOCK = threading.Lock()
ACTIVE_ALERTS = []
EVENT_LISTENERS = []

# Available rural dispatch emergency resources
DISPATCH_RESOURCES = [
    {
        "id": "AMB-01",
        "type": "Ambulancia Medicalizada Tipo II",
        "base": "Hospital Rural San Gabriel",
        "status": "DISPONIBLE",
        "crew": "Dr. Álvarez & Paramédico Gómez",
        "vehicle_type": "4x4 Todo Terreno"
    },
    {
        "id": "MOTO-02",
        "type": "Mototaxi de Rescate Rural con DEA",
        "base": "Puesto de Salud El Roble",
        "status": "DISPONIBLE",
        "crew": "Enfermero Técnico Luis Pari",
        "vehicle_type": "Motocicleta con desfibrilador portátil"
    },
    {
        "id": "CHW-04",
        "type": "Promotor de Salud Comunitario en Moto",
        "base": "Vereda Norte",
        "status": "DISPONIBLE",
        "crew": "Promotora Rosa Medina",
        "vehicle_type": "Bicicleta / Moto de campo"
    }
]


def parse_sms_telemetry(raw_payload: str) -> dict:
    """
    Parses a raw 2G SMS message generated by TinyCardio Edge Node.
    Supported formats:
      1. Human-readable: "TC:D=1024;E=VF;R=96%;HR=182;TS=3412s"
      2. Binary Hex: "544304000160B6102A00E4"
      3. JSON: '{"device_id": 1024, "event_type": "VF", ...}'
    """
    raw_payload = raw_payload.strip()

    # Try JSON
    if raw_payload.startswith("{") and raw_payload.endswith("}"):
        try:
            return json.loads(raw_payload)
        except Exception:
            pass

    # Try Human-Readable SMS Text: "TC:D=1024;E=VF;R=96%;HR=182;TS=3412s"
    if "TC:" in raw_payload or "D=" in raw_payload:
        data = {}
        tokens = re.split(r'[;:,]', raw_payload)
        for token in tokens:
            token = token.strip()
            if "=" in token:
                k, v = token.split("=", 1)
                k, v = k.strip().upper(), v.strip()
                if k == "D":
                    data["device_id"] = int(v)
                elif k == "E":
                    data["event_code"] = v.upper()
                elif k == "R":
                    data["risk_score_pct"] = int(v.replace("%", ""))
                elif k == "HR":
                    data["heart_rate_bpm"] = int(v)
                elif k == "TS":
                    data["timestamp_sec"] = int(v.replace("S", "").replace("s", ""))
        if "device_id" in data:
            return data

    # Fallback default
    return {
        "device_id": 1024,
        "event_code": "VF",
        "risk_score_pct": 95,
        "heart_rate_bpm": 180,
        "timestamp_sec": int(time.time())
    }


def map_event_details(event_code: str) -> tuple:
    """
    Maps clinical event code to medical description and triage severity.
    """
    code = (event_code or "VF").upper()
    if code in ["VF", "VT", "MALIGNANT"]:
        return (
            "Fibrilación / Taquicardia Ventricular Maligna (VFDB)",
            "CRITICO_ROJO",
            "Peligro inminente de parada cardíaca. Despacho urgente con desfibrilador (DEA)."
        )
    elif code in ["ARR", "ARREST", "COLLAPSE"]:
        return (
            "Colapso Autonómico Pre-Paro Cardíaco (SDDB)",
            "CRITICO_ROJO",
            "Muerte Súbita Cardíaca en evolución. Soporte vital avanzado inmediato."
        )
    elif code in ["ISCH", "ISCHEMIA", "ST"]:
        return (
            "Isquemia Miocárdica Aguda / Elevación ST (EDB)",
            "ALERTA_AMARILLO",
            "Sospecha de Síndrome Coronario Agudo. Oxigenoterapia y traslado médico."
        )
    else:
        return (
            "Ritmo Cardíaco Anormal Detectado",
            "OBSERVACION_AZUL",
            "Evaluación por promotor de salud recomendada."
        )


def create_alert_record(parsed_sms: dict) -> dict:
    device_id = parsed_sms.get("device_id", 1024)
    patient = MOCK_PATIENTS.get(device_id, {
        "device_id": device_id,
        "name": f"Paciente Rural (ID #{device_id})",
        "age": 55,
        "gender": "No registrado",
        "blood_type": "Desconocido",
        "location_name": "Sector Rural Remoto (Sin registro previo)",
        "coordinates": {"lat": -13.5350, "lng": -71.9600},
        "medical_history": "Ficha no registrada en el centro de salud",
        "current_medication": "Desconocida",
        "emergency_contact": "Policía / Puesto Comunal",
        "assigned_chw": "Promotor de Guardia",
        "device_battery_pct": 80
    })

    event_code = parsed_sms.get("event_code", "VF")
    event_label, severity, clinical_protocol = map_event_details(event_code)
    risk_pct = parsed_sms.get("risk_score_pct", 92)
    hr_bpm = parsed_sms.get("heart_rate_bpm", 145)

    alert_id = f"ALT-{int(time.time())}-{device_id}"
    created_at = time.time()

    record = {
        "alert_id": alert_id,
        "created_at_epoch": created_at,
        "created_at_iso": time.strftime("%Y-%m-%dT%H:%M:%SZ", time.gmtime(created_at)),
        "status": "PENDIENTE_DESPACHO",  # PENDIENTE_DESPACHO, EN_CAMINO, RESUELTO
        "severity": severity,            # CRITICO_ROJO, ALERTA_AMARILLO
        "golden_hour_seconds_left": 3600,
        "patient": patient,
        "telemetry": {
            "device_id": device_id,
            "event_code": event_code,
            "event_label": event_label,
            "risk_score_pct": risk_pct,
            "heart_rate_bpm": hr_bpm,
            "battery_pct": patient.get("device_battery_pct", 85),
            "raw_sms": f"TC:D={device_id};E={event_code};R={risk_pct}%;HR={hr_bpm};TS={int(created_at)}s",
            "clinical_protocol": clinical_protocol
        },
        "dispatch_info": None
    }
    return record


class TelemetryHubHandler(BaseHTTPRequestHandler):

    def _set_cors_headers(self, content_type="application/json"):
        self.send_header("Access-Control-Allow-Origin", "*")
        self.send_header("Access-Control-Allow-Methods", "GET, POST, OPTIONS")
        self.send_header("Access-Control-Allow-Headers", "Content-Type, Authorization")
        self.send_header("Content-Type", content_type)

    def do_OPTIONS(self):
        self.send_response(200)
        self._set_cors_headers()
        self.end_headers()

    def do_GET(self):
        parsed_url = urlparse(self.path)
        path = parsed_url.path

        # 1. Health check & Summary
        if path == "/" or path == "/api/status":
            self.send_response(200)
            self._set_cors_headers("application/json")
            self.end_headers()
            with ALERTS_LOCK:
                active_count = sum(1 for a in ACTIVE_ALERTS if a["status"] != "RESUELTO")
                critical_count = sum(1 for a in ACTIVE_ALERTS if a["status"] != "RESUELTO" and a["severity"] == "CRITICO_ROJO")
            payload = {
                "service": "TinyCardio Rural Triage & SMS Telemetry Hub",
                "version": "1.0.0",
                "status": "ONLINE",
                "active_alerts_count": active_count,
                "critical_alerts_count": critical_count,
                "registered_patients": len(MOCK_PATIENTS),
                "sms_gateway_ready": True
            }
            self.wfile.write(json.dumps(payload, indent=2).encode('utf-8'))

        # 2. Get Active Alerts List
        elif path == "/api/alerts" or path == "/api/alerts/active":
            self.send_response(200)
            self._set_cors_headers("application/json")
            self.end_headers()
            with ALERTS_LOCK:
                now = time.time()
                for alert in ACTIVE_ALERTS:
                    elapsed = now - alert["created_at_epoch"]
                    alert["golden_hour_seconds_left"] = max(0, int(3600 - elapsed))
                data = list(ACTIVE_ALERTS)
            self.wfile.write(json.dumps({"success": True, "count": len(data), "alerts": data}, indent=2).encode('utf-8'))

        # 3. Get Pre-registered Patients Catalog
        elif path == "/api/patients":
            self.send_response(200)
            self._set_cors_headers("application/json")
            self.end_headers()
            self.wfile.write(json.dumps({"success": True, "patients": list(MOCK_PATIENTS.values())}, indent=2).encode('utf-8'))

        # 4. Get Dispatch Vehicles and Resources
        elif path == "/api/resources":
            self.send_response(200)
            self._set_cors_headers("application/json")
            self.end_headers()
            self.wfile.write(json.dumps({"success": True, "resources": DISPATCH_RESOURCES}, indent=2).encode('utf-8'))

        # 5. Real-Time Server-Sent Events (SSE) Stream
        elif path == "/api/alerts/stream":
            self.send_response(200)
            self.send_header("Access-Control-Allow-Origin", "*")
            self.send_header("Content-Type", "text/event-stream")
            self.send_header("Cache-Control", "no-cache")
            self.send_header("Connection", "keep-alive")
            self.end_headers()

            q = []
            with ALERTS_LOCK:
                EVENT_LISTENERS.append(self.wfile)

            try:
                # Send initial snapshot
                with ALERTS_LOCK:
                    snapshot = json.dumps({"type": "SNAPSHOT", "alerts": ACTIVE_ALERTS})
                self.wfile.write(f"data: {snapshot}\n\n".encode('utf-8'))
                self.wfile.flush()

                # Keep connection alive with heartbeat
                while True:
                    time.sleep(15)
                    self.wfile.write(b": keepalive\n\n")
                    self.wfile.flush()
            except (BrokenPipeError, ConnectionResetError):
                with ALERTS_LOCK:
                    if self.wfile in EVENT_LISTENERS:
                        EVENT_LISTENERS.remove(self.wfile)

        else:
            self.send_response(404)
            self._set_cors_headers()
            self.end_headers()
            self.wfile.write(json.dumps({"error": "Endpoint not found"}).encode('utf-8'))

    def do_POST(self):
        parsed_url = urlparse(self.path)
        path = parsed_url.path

        content_length = int(self.headers.get('Content-Length', 0))
        post_body = self.rfile.read(content_length).decode('utf-8')

        # 1. Incoming SMS Telemetry Endpoint
        if path == "/api/sms/incoming" or path == "/api/alerts/incoming":
            # Could be plain text or JSON
            raw_text = post_body
            if "raw_sms" in post_body or "{" in post_body:
                try:
                    js = json.loads(post_body)
                    raw_text = js.get("raw_sms") or js.get("text") or post_body
                except Exception:
                    pass

            parsed_sms = parse_sms_telemetry(raw_text)
            new_alert = create_alert_record(parsed_sms)

            with ALERTS_LOCK:
                # Prepend to active alerts
                ACTIVE_ALERTS.insert(0, new_alert)

                # Broadcast to SSE listeners
                dead_listeners = []
                msg = f"data: {json.dumps({'type': 'NEW_ALERT', 'alert': new_alert})}\n\n".encode('utf-8')
                for client in EVENT_LISTENERS:
                    try:
                        client.write(msg)
                        client.flush()
                    except Exception:
                        dead_listeners.append(client)
                for dl in dead_listeners:
                    if dl in EVENT_LISTENERS:
                        EVENT_LISTENERS.remove(dl)

            self.send_response(201)
            self._set_cors_headers()
            self.end_headers()
            self.wfile.write(json.dumps({
                "success": True,
                "message": "2G SMS Alert processed and queued for clinical dispatch",
                "alert": new_alert
            }, indent=2).encode('utf-8'))

        # 2. Dispatch Ambulance / Resource Endpoint
        elif path == "/api/dispatch/confirm" or path == "/api/dispatch/ambulance":
            try:
                data = json.loads(post_body)
            except Exception:
                data = {}

            alert_id = data.get("alert_id")
            resource_id = data.get("resource_id", "AMB-01")
            operator_notes = data.get("notes", "Despacho inmediato confirmado desde el centro de salud.")

            matched_alert = None
            with ALERTS_LOCK:
                for alert in ACTIVE_ALERTS:
                    if alert["alert_id"] == alert_id:
                        matched_alert = alert
                        break

            if not matched_alert:
                self.send_response(404)
                self._set_cors_headers()
                self.end_headers()
                self.wfile.write(json.dumps({"success": False, "error": "Alert ID not found"}).encode('utf-8'))
                return

            # Find resource
            resource = next((r for r in DISPATCH_RESOURCES if r["id"] == resource_id), DISPATCH_RESOURCES[0])

            # Update alert state
            matched_alert["status"] = "EN_CAMINO"
            matched_alert["dispatch_info"] = {
                "dispatched_at_iso": time.strftime("%Y-%m-%dT%H:%M:%SZ", time.gmtime()),
                "resource_id": resource["id"],
                "resource_name": resource["type"],
                "estimated_arrival_minutes": 12,
                "operator_notes": operator_notes,
                "return_sms_sent": {
                    "destination_number": matched_alert["patient"].get("emergency_contact", ""),
                    "sms_content": f"TinyCardio: Auxilio despachado. {resource['type']} en camino a su ubicacion. ETA: 12 min. Mantengase recostado."
                }
            }

            # Broadcast update via SSE
            with ALERTS_LOCK:
                msg = f"data: {json.dumps({'type': 'DISPATCH_UPDATE', 'alert': matched_alert})}\n\n".encode('utf-8')
                for client in EVENT_LISTENERS:
                    try:
                        client.write(msg)
                        client.flush()
                    except Exception:
                        pass

            self.send_response(200)
            self._set_cors_headers()
            self.end_headers()
            self.wfile.write(json.dumps({
                "success": True,
                "message": "Resource dispatched successfully and return reassurance SMS queued",
                "alert": matched_alert
            }, indent=2).encode('utf-8'))

        else:
            self.send_response(404)
            self._set_cors_headers()
            self.end_headers()
            self.wfile.write(json.dumps({"error": "Unknown POST endpoint"}).encode('utf-8'))


def seed_initial_demo_alerts():
    """Populate realistic initial alerts for clinical triage simulation"""
    demo_events = [
        {"device_id": 1024, "event_code": "VF", "risk_score_pct": 96, "heart_rate_bpm": 182, "timestamp_sec": int(time.time() - 240)},
        {"device_id": 2048, "event_code": "ISCH", "risk_score_pct": 78, "heart_rate_bpm": 114, "timestamp_sec": int(time.time() - 650)}
    ]
    for ev in demo_events:
        alert = create_alert_record(ev)
        ACTIVE_ALERTS.append(alert)


def run_hub(port=8090):
    seed_initial_demo_alerts()
    server_address = ('0.0.0.0', port)
    httpd = HTTPServer(server_address, TelemetryHubHandler)
    print("=" * 70)
    print(f"TINYCARDIO RURAL TRIAGE & SMS TELEMETRY HUB (PILAR 2)")
    print("=" * 70)
    print(f"  HTTP Server Active:    http://0.0.0.0:{port}")
    print(f"  Active Alerts API:     http://localhost:{port}/api/alerts")
    print(f"  Patients Registry:     http://localhost:{port}/api/patients")
    print(f"  Incoming SMS Webhook:  POST http://localhost:{port}/api/sms/incoming")
    print(f"  Real-time SSE Stream:  http://localhost:{port}/api/alerts/stream")
    print("=" * 70)
    print("Waiting for emergency 2G SMS payloads or dispatch actions... (Ctrl+C to stop)")
    try:
        httpd.serve_forever()
    except KeyboardInterrupt:
        print("\nShutting down TinyCardio SMS Hub...")
        httpd.server_close()


if __name__ == "__main__":
    import argparse
    parser = argparse.ArgumentParser(description="TinyCardio Rural SMS Telemetry Hub")
    parser.add_argument("--port", type=int, default=8090, help="Port to bind (default 8090)")
    args = parser.parse_args()
    run_hub(args.port)
