"""
TinyCardio INT8 Quantizer & C Header Generator
==============================================
Loads trained FP32 weights from 02_model_cpu/model_weights/tinycardio_cpu_weights.npz.
Applies symmetric 8-bit integer quantization to weights (INT8) and preserves bias scaling.
Generates standalone C header file: 03_edge_serialized/include/model_weights.h
Zero dynamic memory allocation, suitable for direct flash ROM inclusion on MCUs.
"""

import os
import sys
import numpy as np
from typing import Tuple


def quantize_symmetric_int8(weights: np.ndarray) -> Tuple[np.ndarray, float]:
    """Quantizes FP32 weights to INT8 [-127, 127] with symmetric scale factor."""
    max_val = np.max(np.abs(weights))
    if max_val < 1e-7:
        scale = 1.0
        q = np.zeros_like(weights, dtype=np.int8)
    else:
        scale = float(max_val / 127.0)
        q = np.clip(np.round(weights / scale), -127, 127).astype(np.int8)
    return q, scale


def generate_c_header(weights_npz: str, output_header: str):
    """Converts model parameters to a C header file with static const arrays."""
    if not os.path.exists(weights_npz):
        raise FileNotFoundError(f"Weights file not found: {weights_npz}")

    data = np.load(weights_npz)
    w_conv1 = data['w_conv1']  # (5, 1, 8)
    b_conv1 = data['b_conv1']  # (8,)
    w_conv2 = data['w_conv2']  # (3, 8, 16)
    b_conv2 = data['b_conv2']  # (16,)
    w_dense = data['w_dense']  # (16, 1)
    b_dense = data['b_dense']  # (1,)

    # Quantize weights to INT8
    q_conv1, s_conv1 = quantize_symmetric_int8(w_conv1)
    q_conv2, s_conv2 = quantize_symmetric_int8(w_conv2)
    q_dense, s_dense = quantize_symmetric_int8(w_dense)

    os.makedirs(os.path.dirname(output_header), exist_ok=True)

    def format_c_array_i8(arr: np.ndarray, name: str) -> str:
        flat = arr.ravel()
        vals = ", ".join(str(int(x)) for x in flat)
        return f"static const int8_t {name}[{len(flat)}] = {{\n    {vals}\n}};\n"

    def format_c_array_f32(arr: np.ndarray, name: str) -> str:
        flat = arr.ravel()
        vals = ", ".join(f"{float(x):.6f}f" for x in flat)
        return f"static const float {name}[{len(flat)}] = {{\n    {vals}\n}};\n"

    total_bytes = (q_conv1.size * 1 + b_conv1.size * 4 +
                   q_conv2.size * 1 + b_conv2.size * 4 +
                   q_dense.size * 1 + b_dense.size * 4)

    content = f"""/**
 * TinyCardio INT8 Serialized Model Weights
 * Automatically generated by quantize_int8.py
 * Target Architectures: ARM Cortex-M0+ (RP2040), Cortex-M4 (STM32), ESP32-C3
 * Flash Memory Footprint: {total_bytes} bytes
 */

#ifndef MODEL_WEIGHTS_H
#define MODEL_WEIGHTS_H

#include <stdint.h>

#define TINYCARDIO_INPUT_LEN       250
#define TINYCARDIO_CONV1_KERNEL    5
#define TINYCARDIO_CONV1_IN_CH     1
#define TINYCARDIO_CONV1_OUT_CH    8
#define TINYCARDIO_CONV1_STRIDE    2
#define TINYCARDIO_CONV1_OUT_LEN   125

#define TINYCARDIO_CONV2_KERNEL    3
#define TINYCARDIO_CONV2_IN_CH     8
#define TINYCARDIO_CONV2_OUT_CH    16
#define TINYCARDIO_CONV2_STRIDE    2
#define TINYCARDIO_CONV2_OUT_LEN   63

#define TINYCARDIO_DENSE_IN_FEAT   16
#define TINYCARDIO_DENSE_OUT_FEAT  1

/* Scaling Factors for Weights */
#define TINYCARDIO_SCALE_CONV1     {s_conv1:.8f}f
#define TINYCARDIO_SCALE_CONV2     {s_conv2:.8f}f
#define TINYCARDIO_SCALE_DENSE     {s_dense:.8f}f
#define TINYCARDIO_TOTAL_WEIGHTS_BYTES {total_bytes}

/* Layer 1: Conv1D Weights (INT8) and Bias (Float) */
{format_c_array_i8(q_conv1, "g_tinycardio_conv1_w")}
{format_c_array_f32(b_conv1, "g_tinycardio_conv1_b")}

/* Layer 2: Conv1D Weights (INT8) and Bias (Float) */
{format_c_array_i8(q_conv2, "g_tinycardio_conv2_w")}
{format_c_array_f32(b_conv2, "g_tinycardio_conv2_b")}

/* Layer 3: Dense Weights (INT8) and Bias (Float) */
{format_c_array_i8(q_dense, "g_tinycardio_dense_w")}
{format_c_array_f32(b_dense, "g_tinycardio_dense_b")}

#endif /* MODEL_WEIGHTS_H */
"""
    with open(output_header, 'w', encoding='utf-8') as f:
        f.write(content)

    print(f"Serialized INT8 model exported to: {output_header}")
    print(f"Total Model Weight Size in ROM: {total_bytes} bytes ({total_bytes / 1024.0:.2f} KB).")


if __name__ == '__main__':
    weights_path = '02_model_cpu/model_weights/tinycardio_cpu_weights.npz'
    out_h = '03_edge_serialized/include/model_weights.h'
    if not os.path.exists(weights_path):
        print(f"Weights file not found: {weights_path}. Train the model first.")
        sys.exit(0)
    generate_c_header(weights_path, out_h)
